# Generated by Django 4.1 on 2022-10-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
